import type { NoteSheet } from "@/lib/types"
import { getApprover } from "@/lib/mock/approvers"
import { ruleLibrary } from "@/lib/mock/rules"

export const noteSheets: NoteSheet[] = [
  {
    id: "ns-1042",
    subject: "Sanction for procurement of Digital Storage Oscilloscopes, Robotics Laboratory",
    category: "Lab Equipment Purchase",
    requester: "Ananya Bhardwaj",
    department: "Robotics & Automation",
    amount: 80000,
    status: "Pending Approval",
    currentStage: "Comptroller of Finance",
    createdAt: "2026-08-14T09:20:00+05:30",
    updatedAt: "2026-08-18T11:05:00+05:30",
    prompt: "Sanction ₹80,000 for oscilloscopes in Robotics Lab",
    draftText:
      "Subject: Sanction for procurement of Digital Storage Oscilloscopes for the Robotics Laboratory, Department of Robotics & Automation.\n\nThe Department of Robotics & Automation has proposed procurement of four 4-channel digital storage oscilloscopes (100MHz bandwidth) for the undergraduate Robotics Laboratory, to support signal-analysis modules introduced in the revised curriculum. In accordance with [GFR Rule 153], three comparative quotations were obtained from empanelled vendors, and the Local Purchase Committee has recommended M/s Metrotech Instruments as the L-1 compliant bidder at a total quoted price of ₹80,000 inclusive of applicable GST ([Finance Circular GST-2]).\n\nThe proposed expenditure is within the delegated financial powers of the Head of Department for laboratory equipment as prescribed under [DFPR Schedule V, Item 12], and is proposed to be met from the Department's annual Laboratory Equipment budget head for FY 2026–27.\n\nIt is requested that sanction be accorded for an expenditure of ₹80,000 (Rupees Eighty Thousand only) for the above purchase, subject to submission of an installation and demonstration report within 30 days of delivery.",
    justification:
      "The existing analog oscilloscopes in the Robotics Laboratory (procured in 2016) do not support the digital waveform capture required by the revised Signal Processing for Robotics module introduced this semester. Without this upgrade, approximately 140 third-year students will be unable to complete the mandated lab component this term.",
    aiReasoning:
      "The draft was generated by matching the request category (Lab Equipment Purchase) against 2 retrieved precedents with similar equipment class and amount range (prec-002, prec-007). Rule citations were selected based on: (1) amount falling under the ₹2,50,000 Local Purchase Committee threshold, triggering GFR Rule 153 rather than open tender rules; (2) GST treatment flagged per standing Finance Circular; (3) delegated authority ceiling check against DFPR Schedule V confirming HoD-level sanction is sufficient without Finance Committee escalation. Budget line items were parsed from the free-text prompt and cross-checked against the vendor quotation pattern seen in precedent 002.",
    budgetItems: [
      { id: "bi-1", item: "Digital Storage Oscilloscope, 100MHz 4-channel", quantity: 4, unitCost: 16949, gstPercent: 18 },
    ],
    citations: [
      { id: "c1", ...requireRule("GFR Rule 153") },
      { id: "c2", ...requireRule("Finance Circular GST-2") },
      { id: "c3", ...requireRule("DFPR Schedule V, Item 12") },
    ],
    requiredDocuments: [
      { id: "rd-1", name: "Comparative statement of quotations (3 vendors)", attached: true },
      { id: "rd-2", name: "Local Purchase Committee recommendation", attached: true },
      { id: "rd-3", name: "Budget head certification from Accounts", attached: false },
      { id: "rd-4", name: "Vendor GST registration certificate", attached: true },
    ],
    wordingSuggestions: [
      {
        id: "ws-1",
        before: "The Department of Robotics & Automation has proposed procurement of four",
        after: "The Department of Robotics & Automation hereby proposes the procurement of four",
        reason: "Formal note sheets conventionally use present-tense 'hereby proposes' for the operative sentence.",
        status: "pending",
      },
      {
        id: "ws-2",
        before: "It is requested that sanction be accorded for an expenditure of ₹80,000",
        after: "It is respectfully requested that sanction be accorded for an expenditure of ₹80,000",
        reason: "Convention in this university's note sheets includes 'respectfully' when addressing sanctioning authority above HoD level.",
        status: "pending",
      },
    ],
    approvalStages: [
      { id: "st-1", name: "Departmental Review", order: 1, approvers: [approvedApprover("apr-01", "Ananya Bhardwaj", "2026-08-14T15:40:00+05:30")] },
      { id: "st-2", name: "Purchase & Accounts Verification", order: 2, approvers: [approvedApprover("apr-03", "Deepak Chauhan", "2026-08-16T10:12:00+05:30"), approvedApprover("apr-04", "Ritika Sehgal", "2026-08-16T14:30:00+05:30")] },
      { id: "st-3", name: "Finance Sanction", order: 3, approvers: [pendingApprover("apr-05")] },
      { id: "st-4", name: "Dean's Office", order: 4, approvers: [pendingApprover("apr-08")] },
    ],
    precedentIds: ["prec-002", "prec-007"],
  },
  {
    id: "ns-1041",
    subject: "Sanction for 3-axis CNC Trainer Kit, Manufacturing Processes Laboratory",
    category: "Lab Equipment Purchase",
    requester: "Rohan Malhotra",
    department: "Mechanical Engineering",
    amount: 62500,
    status: "Approved",
    currentStage: "Completed",
    createdAt: "2026-07-22T10:00:00+05:30",
    updatedAt: "2026-07-30T16:45:00+05:30",
    prompt: "Sanction for a CNC trainer kit for the Manufacturing Processes lab, around ₹62,500",
    draftText:
      "Subject: Sanction for purchase of 3-axis CNC Trainer Kit for Manufacturing Processes Laboratory, Department of Mechanical Engineering.\n\nThe Department has requested procurement of one 3-axis CNC Trainer Kit for undergraduate laboratory instruction under the Manufacturing Processes course. Three comparative quotations were obtained as required under [GFR Rule 153]. M/s EduTech Systems was found L-1 compliant at a quoted price of ₹62,500 inclusive of GST.\n\nSanction is accorded for an expenditure of ₹62,500 (Rupees Sixty-Two Thousand Five Hundred only) from the Laboratory Equipment head, subject to submission of installation and demonstration report within 30 days of delivery.",
    justification:
      "The Manufacturing Processes course (ME-304) requires hands-on CNC programming exposure per the revised AICTE model curriculum; the department currently has no functional CNC training unit.",
    aiReasoning:
      "Matched against precedent 001 (same equipment class, same department). GFR Rule 153 selected as the amount falls within the Local Purchase Committee threshold. No escalation to Finance Committee required per DFPR Schedule V.",
    budgetItems: [{ id: "bi-1", item: "3-axis CNC Trainer Kit with controller", quantity: 1, unitCost: 52966, gstPercent: 18 }],
    citations: [{ id: "c1", ...requireRule("GFR Rule 153") }],
    requiredDocuments: [
      { id: "rd-1", name: "Comparative statement of quotations (3 vendors)", attached: true },
      { id: "rd-2", name: "Local Purchase Committee recommendation", attached: true },
      { id: "rd-3", name: "Budget head certification from Accounts", attached: true },
    ],
    wordingSuggestions: [],
    approvalStages: [
      { id: "st-1", name: "Departmental Review", order: 1, approvers: [approvedApprover("apr-02", "Sunita Rawal", "2026-07-23T09:00:00+05:30")] },
      { id: "st-2", name: "Purchase & Accounts Verification", order: 2, approvers: [approvedApprover("apr-03", "Deepak Chauhan", "2026-07-25T11:00:00+05:30"), approvedApprover("apr-04", "Ritika Sehgal", "2026-07-25T12:00:00+05:30")] },
      { id: "st-3", name: "Finance Sanction", order: 3, approvers: [approvedApprover("apr-05", "Farhan Iqbal", "2026-07-28T15:00:00+05:30")] },
      { id: "st-4", name: "Dean's Office", order: 4, approvers: [approvedApprover("apr-08", "Vandana Suri", "2026-07-30T16:45:00+05:30")] },
    ],
    precedentIds: ["prec-001"],
  },
  {
    id: "ns-1039",
    subject: "Honorarium for guest resource persons — Industry 4.0 Workshop Series",
    category: "Guest Faculty Honorarium",
    requester: "Nalin Kapoor",
    department: "Robotics & Automation",
    amount: 24000,
    status: "Approved",
    currentStage: "Completed",
    createdAt: "2026-06-10T09:00:00+05:30",
    updatedAt: "2026-06-14T13:20:00+05:30",
    prompt: "Honorarium for two guest speakers, 8 sessions total, Industry 4.0 workshop",
    draftText:
      "Subject: Sanction of honorarium for guest resource persons — Industry 4.0 Workshop Series.\n\nThe Department organised an 8-session workshop series on Industry 4.0 and Industrial IoT, conducted by two external resource persons. Each delivered 4 sessions at the departmentally approved rate of ₹3,000 per session as per [Honorarium Circular 7/2019].\n\nTotal honorarium payable: ₹3,000 x 8 sessions = ₹24,000, inclusive of applicable TDS to be deducted at source. Sanction is accorded for ₹24,000 (Rupees Twenty-Four Thousand only) from the Departmental Training & Workshop head.",
    justification: "Workshop directly supports the Industry 4.0 elective and was attended by 96 final-year students as part of mandatory skill-development hours.",
    aiReasoning: "Rate matched against Honorarium Circular 7/2019 ceiling of ₹3,000/session; total computed as sessions × rate. Matched precedent 003 with identical structure.",
    budgetItems: [{ id: "bi-1", item: "Guest resource person honorarium (8 sessions @ ₹3,000)", quantity: 8, unitCost: 3000, gstPercent: 0 }],
    citations: [{ id: "c1", ...requireRule("Honorarium Circular 7/2019") }],
    requiredDocuments: [
      { id: "rd-1", name: "Session attendance sheets", attached: true },
      { id: "rd-2", name: "Resource person CV / profile", attached: true },
      { id: "rd-3", name: "PAN details for TDS", attached: true },
    ],
    wordingSuggestions: [],
    approvalStages: [
      { id: "st-1", name: "Departmental Review", order: 1, approvers: [approvedApprover("apr-01", "Nalin Kapoor", "2026-06-10T09:30:00+05:30")] },
      { id: "st-2", name: "Accounts Verification", order: 2, approvers: [approvedApprover("apr-04", "Ritika Sehgal", "2026-06-12T10:00:00+05:30")] },
      { id: "st-3", name: "Finance Sanction", order: 3, approvers: [approvedApprover("apr-05", "Farhan Iqbal", "2026-06-14T13:20:00+05:30")] },
    ],
    precedentIds: ["prec-003"],
  },
  {
    id: "ns-1037",
    subject: "Budget sanction for Annual Techfest 'Vortex 2026'",
    category: "Event/Fest Expenditure",
    requester: "Priya Nambiar",
    department: "Student Welfare",
    amount: 412000,
    status: "Pending Approval",
    currentStage: "Dean, Student Welfare",
    createdAt: "2026-08-01T09:00:00+05:30",
    updatedAt: "2026-08-10T17:00:00+05:30",
    prompt: "Budget for annual techfest Vortex 2026, roughly 4.1 lakh covering venue, prizes, hospitality",
    draftText:
      "Subject: Sanction of budget for Annual Technical Festival 'Vortex 2026'.\n\nThe Student Council has submitted a detailed budget for the three-day annual technical festival Vortex 2026, comprising venue and stage setup, hospitality and refreshments, prize money across 14 competitive events, guest speaker honoraria, and promotional material, in accordance with [Event Expenditure Guideline 9].\n\nIt is requested that sanction be accorded for a total expenditure of ₹4,12,000 (Rupees Four Lakh Twelve Thousand only), to be disbursed against actuals with utilisation certificate to be submitted within 15 days of event conclusion.",
    justification:
      "Vortex is the flagship annual student event and directly supports the university's outreach and student engagement targets; last year's edition (Vortex 2024) recorded 3,200+ external participants.",
    aiReasoning:
      "Line items decomposed from prompt into 5 standard fest cost categories, matched to precedent 004 structure. Total checked against Student Activity Fund ceiling under Event Expenditure Guideline 9 — within allocated limit for current year.",
    budgetItems: [
      { id: "bi-1", item: "Venue and stage setup", quantity: 1, unitCost: 102000, gstPercent: 18 },
      { id: "bi-2", item: "Hospitality and refreshments", quantity: 1, unitCost: 72000, gstPercent: 5 },
      { id: "bi-3", item: "Prize money (14 events)", quantity: 14, unitCost: 9000, gstPercent: 0 },
      { id: "bi-4", item: "Guest speaker honoraria", quantity: 1, unitCost: 45000, gstPercent: 0 },
      { id: "bi-5", item: "Promotional and print material", quantity: 1, unitCost: 65000, gstPercent: 18 },
    ],
    citations: [{ id: "c1", ...requireRule("Event Expenditure Guideline 9") }],
    requiredDocuments: [
      { id: "rd-1", name: "Detailed event budget (line-item)", attached: true },
      { id: "rd-2", name: "Student Council resolution", attached: true },
      { id: "rd-3", name: "Previous year utilisation certificate", attached: false },
    ],
    wordingSuggestions: [
      {
        id: "ws-1",
        before: "It is requested that sanction be accorded",
        after: "It is respectfully requested that sanction be accorded",
        reason: "Convention for requests routed to Dean-level authority.",
        status: "pending",
      },
    ],
    approvalStages: [
      { id: "st-1", name: "Student Council Review", order: 1, approvers: [approvedApprover("apr-06", "Priya Nambiar", "2026-08-02T09:00:00+05:30")] },
      { id: "st-2", name: "Accounts Verification", order: 2, approvers: [approvedApprover("apr-04", "Ritika Sehgal", "2026-08-06T14:00:00+05:30")] },
      { id: "st-3", name: "Dean, Student Welfare", order: 3, approvers: [pendingApprover("apr-06")] },
      { id: "st-4", name: "Vice Chancellor", order: 4, approvers: [pendingApprover("apr-10")] },
    ],
    precedentIds: ["prec-004"],
  },
  {
    id: "ns-1035",
    subject: "TA/DA sanction for student delegation to National Robotics Championship 2026",
    category: "Student Travel/TA-DA",
    requester: "Ishaan Verma",
    department: "Robotics & Automation",
    amount: 61800,
    status: "Rejected",
    currentStage: "Returned to Requester",
    createdAt: "2026-05-18T09:00:00+05:30",
    updatedAt: "2026-05-24T12:15:00+05:30",
    prompt: "TA/DA for 6 students + 1 faculty travelling to national robotics championship",
    draftText:
      "Subject: Sanction of TA/DA for student delegation to National Robotics Championship 2026.\n\nA six-member student team along with one faculty mentor has been selected to represent the University. Travel is proposed by AC-3 tier rail as per [TA/DA Rule 4.2], along with daily allowance for 3 days.\n\nIt is requested that sanction be accorded for ₹61,800 (Rupees Sixty-One Thousand Eight Hundred only) from the Student Travel Grant head.",
    justification: "Team qualified in the top 12 nationally; participation strengthens the university's standing in inter-collegiate robotics competitions.",
    aiReasoning: "Computed as rail fare (7 pax) + DA (7 × 3 days × ₹600) + registration fee, matched against precedent 005 structure and TA/DA Rule 4.2 entitlement.",
    budgetItems: [
      { id: "bi-1", item: "AC-3 tier rail fare (7 participants, round trip)", quantity: 7, unitCost: 4500, gstPercent: 0 },
      { id: "bi-2", item: "Daily allowance (7 participants × 3 days)", quantity: 21, unitCost: 600, gstPercent: 0 },
      { id: "bi-3", item: "Event registration fee", quantity: 1, unitCost: 14100, gstPercent: 0 },
    ],
    citations: [{ id: "c1", ...requireRule("TA/DA Rule 4.2") }],
    requiredDocuments: [
      { id: "rd-1", name: "Event invitation / qualification proof", attached: true },
      { id: "rd-2", name: "Travel Grant fund balance certificate", attached: false },
      { id: "rd-3", name: "List of participating students with roll numbers", attached: true },
    ],
    wordingSuggestions: [],
    approvalStages: [
      { id: "st-1", name: "Departmental Review", order: 1, approvers: [approvedApprover("apr-01", "Nalin Kapoor", "2026-05-19T09:00:00+05:30")] },
      {
        id: "st-2",
        name: "Accounts Verification",
        order: 2,
        approvers: [rejectedApprover("apr-04", "Ritika Sehgal", "2026-05-24T12:15:00+05:30", "Student Travel Grant head for this quarter is already exhausted; resubmit against next quarter's allocation or seek supplementary grant approval from the Registrar.")],
      },
    ],
    precedentIds: ["prec-005"],
  },
  {
    id: "ns-1033",
    subject: "Annual activity budget sanction for Robotics Club, AY 2026–27",
    category: "Club Budget",
    requester: "Tanvi Oberoi",
    department: "Robotics & Automation",
    amount: 74500,
    status: "Draft",
    currentStage: "Not yet submitted",
    createdAt: "2026-08-17T15:30:00+05:30",
    updatedAt: "2026-08-17T15:30:00+05:30",
    prompt: "Draft the annual budget note for the robotics club, similar to last year, around 74,500",
    draftText:
      "Subject: Sanction of Annual Activity Budget for Robotics Club, AY 2026–27.\n\nThe Robotics Club has submitted its annual activity proposal comprising component and prototyping material, competition entry and travel contingency, and expert mentorship sessions, within the ceiling prescribed under [Club Budget Rule 3.1].\n\nIt is requested that sanction be accorded for ₹74,500 (Rupees Seventy-Four Thousand Five Hundred only), to be released in two tranches, the second against submission of utilisation certificate for the first.",
    justification: "Club activity plan mirrors last year's approved structure with a 5% material cost adjustment for inflation; club has an active roster of 68 members.",
    aiReasoning: "Directly matched precedent 006 (same club, prior year) with minor cost adjustment. Confirmed proposal remains within the ₹75,000 annual ceiling under Club Budget Rule 3.1.",
    budgetItems: [
      { id: "bi-1", item: "Component and prototyping material", quantity: 1, unitCost: 32000, gstPercent: 18 },
      { id: "bi-2", item: "Competition entry and travel contingency", quantity: 1, unitCost: 22000, gstPercent: 0 },
      { id: "bi-3", item: "Expert mentorship sessions", quantity: 1, unitCost: 14500, gstPercent: 0 },
    ],
    citations: [{ id: "c1", ...requireRule("Club Budget Rule 3.1") }],
    requiredDocuments: [
      { id: "rd-1", name: "Club activity proposal", attached: true },
      { id: "rd-2", name: "Previous tranche utilisation certificate", attached: false },
      { id: "rd-3", name: "Faculty advisor endorsement", attached: false },
    ],
    wordingSuggestions: [],
    approvalStages: [
      { id: "st-1", name: "Departmental Review", order: 1, approvers: [pendingApprover("apr-01")] },
      { id: "st-2", name: "Accounts Verification", order: 2, approvers: [pendingApprover("apr-04")] },
    ],
    precedentIds: ["prec-006"],
  },
]

function pendingApprover(id: string) {
  return getApprover(id)
}

function approvedApprover(id: string, signature: string, signedAt: string) {
  const a = getApprover(id)
  return { ...a, status: "Approved" as const, signature, signedAt }
}

function rejectedApprover(id: string, signature: string, signedAt: string, rejectionReason: string) {
  const a = getApprover(id)
  return { ...a, status: "Rejected" as const, signature, signedAt, rejectionReason }
}

function requireRule(codeOrId: string) {
  const found = ruleLibrary.find((r) => r.code === codeOrId || r.id === codeOrId)
  if (!found) throw new Error(`Unknown rule reference: ${codeOrId}`)
  return { code: found.code, title: found.title, excerpt: found.excerpt, sourceDoc: found.sourceDoc }
}

export function getNoteSheet(id: string): NoteSheet | undefined {
  return noteSheets.find((n) => n.id === id)
}
